### ISSUE TITLE
👍 很赞的项目

### ISSUE THREAD

**Issue by hustcc** [glfeng318/rg2#4]
建议：

1. 不进行图表类型的封装，不二次封装数据结构，减少自己的维护成本，也降低开发者的理解成本
2. 建议升级 G2Plot v2 版本，更加稳定

我是 G2 G2Plot 开发的同学，最近做了 PyG2Plot 后，才发现你也封装了 Py R 的，很赞。

可以采纳上述建议，我在官网也可以收录一下！如果可以的话，加个微信，我微信在我首页有。

**Comment by glfeng318** [comment]
谢谢。
1会考虑一下，封装类型和数据结构这个维护确实很头疼，我本身不太熟悉JavaScript或者typescript，从自己作为数据分析用户，可能直接更希望使用pandas data.frame数据直接画图了，就比如我有一个dataframe我熟悉它每一列的业务含义，希望用dataframe和列名就能做个图。
至于V2版本，你们当初刚开始这个版本的时候就想着升级了，然后想等着api稳定下来再做，然后就忙其他事没动这个了。

**Comment by hustcc** [comment]
> 谢谢。
> 1会考虑一下，封装类型和数据结构这个维护确实很头疼，我本身不太熟悉JavaScript或者typescript，从自己作为数据分析用户，可能直接更希望使用pandas data.frame数据直接画图了，就比如我有一个dataframe我熟悉它每一列的业务含义，希望用dataframe和列名就能做个图。
> 至于V2版本，你们当初刚开始这个版本的时候就想着升级了，然后想等着api稳定下来再做，然后就忙其他事没动这个了。

V2 目前已经发布很久了，在内部几个大业务中替换了，虽然也有不少的 bug，但是比 v1 会好很多很多，架构上也可以持续迭代了。

如果在升级过程中有 js  ts 的问题，我可以帮忙处理。
